### ISSUE TITLE
Composer require package not found

### ISSUE THREAD

**Issue by affektde** [stechstudio/laravel-record#1]
![image](https://user-images.githubusercontent.com/5022192/102090071-4c4cb000-3e1d-11eb-9f2f-c15097b8494e.png)

Is the package possibly only installable via `stechstudio/laravel-record` right now?

`sts/laravel-record` does not seem to work. That's what it says in the README at the moment.

**Comment by jszobody** [comment]
Yep, it's `stechstudio/laravel-record` just fixed the readme. Thanks!
